//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContainerWebServiceClient.KonteynerWS_Gateway {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tasima", Namespace="http://bilgewebservisler.ABC.gov.tr")]
    [System.SerializableAttribute()]
    public partial class Tasima : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OzetBeyanNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TasitAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeferNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TasitNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GelisGidisTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GelisGidisBildirimNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsletmeKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YonuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ContainerWebServiceClient.KonteynerWS_Gateway.TasimaDetay[] tasimaDetaylariField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tescilNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OzetBeyanNo {
            get {
                return this.OzetBeyanNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OzetBeyanNoField, value) != true)) {
                    this.OzetBeyanNoField = value;
                    this.RaisePropertyChanged("OzetBeyanNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TasitAdi {
            get {
                return this.TasitAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.TasitAdiField, value) != true)) {
                    this.TasitAdiField = value;
                    this.RaisePropertyChanged("TasitAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string SeferNo {
            get {
                return this.SeferNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SeferNoField, value) != true)) {
                    this.SeferNoField = value;
                    this.RaisePropertyChanged("SeferNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string TasitNo {
            get {
                return this.TasitNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TasitNoField, value) != true)) {
                    this.TasitNoField = value;
                    this.RaisePropertyChanged("TasitNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime GelisGidisTarihi {
            get {
                return this.GelisGidisTarihiField;
            }
            set {
                if ((this.GelisGidisTarihiField.Equals(value) != true)) {
                    this.GelisGidisTarihiField = value;
                    this.RaisePropertyChanged("GelisGidisTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string GelisGidisBildirimNo {
            get {
                return this.GelisGidisBildirimNoField;
            }
            set {
                if ((object.ReferenceEquals(this.GelisGidisBildirimNoField, value) != true)) {
                    this.GelisGidisBildirimNoField = value;
                    this.RaisePropertyChanged("GelisGidisBildirimNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string IsletmeKodu {
            get {
                return this.IsletmeKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.IsletmeKoduField, value) != true)) {
                    this.IsletmeKoduField = value;
                    this.RaisePropertyChanged("IsletmeKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Tipi {
            get {
                return this.TipiField;
            }
            set {
                if ((object.ReferenceEquals(this.TipiField, value) != true)) {
                    this.TipiField = value;
                    this.RaisePropertyChanged("Tipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Yonu {
            get {
                return this.YonuField;
            }
            set {
                if ((object.ReferenceEquals(this.YonuField, value) != true)) {
                    this.YonuField = value;
                    this.RaisePropertyChanged("Yonu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public ContainerWebServiceClient.KonteynerWS_Gateway.TasimaDetay[] tasimaDetaylari {
            get {
                return this.tasimaDetaylariField;
            }
            set {
                if ((object.ReferenceEquals(this.tasimaDetaylariField, value) != true)) {
                    this.tasimaDetaylariField = value;
                    this.RaisePropertyChanged("tasimaDetaylari");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string tescilNo {
            get {
                return this.tescilNoField;
            }
            set {
                if ((object.ReferenceEquals(this.tescilNoField, value) != true)) {
                    this.tescilNoField = value;
                    this.RaisePropertyChanged("tescilNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TasimaDetay", Namespace="http://bilgewebservisler.ABC.gov.tr")]
    [System.SerializableAttribute()]
    public partial class TasimaDetay : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TescilNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TasimaSenediNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KapAdediField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TuruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KonteynerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NetAgirlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsyaCinsiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BulunduguYerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TescilNo {
            get {
                return this.TescilNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TescilNoField, value) != true)) {
                    this.TescilNoField = value;
                    this.RaisePropertyChanged("TescilNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string TasimaSenediNo {
            get {
                return this.TasimaSenediNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TasimaSenediNoField, value) != true)) {
                    this.TasimaSenediNoField = value;
                    this.RaisePropertyChanged("TasimaSenediNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int KapAdedi {
            get {
                return this.KapAdediField;
            }
            set {
                if ((this.KapAdediField.Equals(value) != true)) {
                    this.KapAdediField = value;
                    this.RaisePropertyChanged("KapAdedi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Turu {
            get {
                return this.TuruField;
            }
            set {
                if ((object.ReferenceEquals(this.TuruField, value) != true)) {
                    this.TuruField = value;
                    this.RaisePropertyChanged("Turu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string KonteynerNo {
            get {
                return this.KonteynerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.KonteynerNoField, value) != true)) {
                    this.KonteynerNoField = value;
                    this.RaisePropertyChanged("KonteynerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal NetAgirlik {
            get {
                return this.NetAgirlikField;
            }
            set {
                if ((this.NetAgirlikField.Equals(value) != true)) {
                    this.NetAgirlikField = value;
                    this.RaisePropertyChanged("NetAgirlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string EsyaCinsi {
            get {
                return this.EsyaCinsiField;
            }
            set {
                if ((object.ReferenceEquals(this.EsyaCinsiField, value) != true)) {
                    this.EsyaCinsiField = value;
                    this.RaisePropertyChanged("EsyaCinsi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string BulunduguYer {
            get {
                return this.BulunduguYerField;
            }
            set {
                if ((object.ReferenceEquals(this.BulunduguYerField, value) != true)) {
                    this.BulunduguYerField = value;
                    this.RaisePropertyChanged("BulunduguYer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sonuc", Namespace="http://bilgewebservisler.ABC.gov.tr")]
    [System.SerializableAttribute()]
    public partial class Sonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IslemSonucuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ContainerWebServiceClient.KonteynerWS_Gateway.Hata[] HatalarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TescilNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IslemSonucu {
            get {
                return this.IslemSonucuField;
            }
            set {
                if ((this.IslemSonucuField.Equals(value) != true)) {
                    this.IslemSonucuField = value;
                    this.RaisePropertyChanged("IslemSonucu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ContainerWebServiceClient.KonteynerWS_Gateway.Hata[] Hatalar {
            get {
                return this.HatalarField;
            }
            set {
                if ((object.ReferenceEquals(this.HatalarField, value) != true)) {
                    this.HatalarField = value;
                    this.RaisePropertyChanged("Hatalar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string TescilNo {
            get {
                return this.TescilNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TescilNoField, value) != true)) {
                    this.TescilNoField = value;
                    this.RaisePropertyChanged("TescilNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hata", Namespace="http://bilgewebservisler.ABC.gov.tr")]
    [System.SerializableAttribute()]
    public partial class Hata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataAciklamasiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataKoduField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HataAciklamasi {
            get {
                return this.HataAciklamasiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataAciklamasiField, value) != true)) {
                    this.HataAciklamasiField = value;
                    this.RaisePropertyChanged("HataAciklamasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.HataKoduField, value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YerDegisiklikSonuc", Namespace="http://bilgewebservisler.ABC.gov.tr")]
    [System.SerializableAttribute()]
    public partial class YerDegisiklikSonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IslemSonucuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ContainerWebServiceClient.KonteynerWS_Gateway.Hata[] HatalarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AciklamaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IslemSonucu {
            get {
                return this.IslemSonucuField;
            }
            set {
                if ((this.IslemSonucuField.Equals(value) != true)) {
                    this.IslemSonucuField = value;
                    this.RaisePropertyChanged("IslemSonucu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ContainerWebServiceClient.KonteynerWS_Gateway.Hata[] Hatalar {
            get {
                return this.HatalarField;
            }
            set {
                if ((object.ReferenceEquals(this.HatalarField, value) != true)) {
                    this.HatalarField = value;
                    this.RaisePropertyChanged("Hatalar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bilgewebservisler.ABC.gov.tr", ConfigurationName="KonteynerWS_Gateway.IKonteyner")]
    public interface IKonteyner {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bilgewebservisler.ABC.gov.tr/IKonteyner/TasimaBilgileriKaydet", ReplyAction="http://bilgewebservisler.ABC.gov.tr/IKonteyner/TasimaBilgileriKaydetResponse")]
        ContainerWebServiceClient.KonteynerWS_Gateway.Sonuc TasimaBilgileriKaydet(ContainerWebServiceClient.KonteynerWS_Gateway.Tasima tasimalar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bilgewebservisler.ABC.gov.tr/IKonteyner/KonteynerYeriniDegistir", ReplyAction="http://bilgewebservisler.ABC.gov.tr/IKonteyner/KonteynerYeriniDegistirResponse" +
            "")]
        ContainerWebServiceClient.KonteynerWS_Gateway.YerDegisiklikSonuc KonteynerYeriniDegistir(string bildirimNo, string konteynerNo, string bulunduguYer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKonteynerChannel : ContainerWebServiceClient.KonteynerWS_Gateway.IKonteyner, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KonteynerClient : System.ServiceModel.ClientBase<ContainerWebServiceClient.KonteynerWS_Gateway.IKonteyner>, ContainerWebServiceClient.KonteynerWS_Gateway.IKonteyner {
        
        public KonteynerClient() {
        }
        
        public KonteynerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KonteynerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KonteynerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KonteynerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ContainerWebServiceClient.KonteynerWS_Gateway.Sonuc TasimaBilgileriKaydet(ContainerWebServiceClient.KonteynerWS_Gateway.Tasima tasimalar) {
            return base.Channel.TasimaBilgileriKaydet(tasimalar);
        }
        
        public ContainerWebServiceClient.KonteynerWS_Gateway.YerDegisiklikSonuc KonteynerYeriniDegistir(string bildirimNo, string konteynerNo, string bulunduguYer) {
            return base.Channel.KonteynerYeriniDegistir(bildirimNo, konteynerNo, bulunduguYer);
        }
    }
}
