//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EmployeeDesignation.YetkiKontrol {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="YetkileriGetirSoap", Namespace="http://ABC.gov.tr/")]
    public partial class YetkileriGetir : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback KullaniciYetkileriOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullaniciYetkileriveKimlikBilgileriOperationCompleted;
        
        private System.Threading.SendOrPostCallback EBelgeKullaniciOperationCompleted;
        
        private System.Threading.SendOrPostCallback TCGBKullaniciOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullanicininYetkileriOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullaniciYetkileriDataSetXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback KullaniciYetkileriArrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMd5HashOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public YetkileriGetir() {
            this.Url = global::EmployeeDesignation.Properties.Settings.Default.PersonelAtama_YetkiKontrol_YetkileriGetir;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event KullaniciYetkileriCompletedEventHandler KullaniciYetkileriCompleted;
        
        /// <remarks/>
        public event KullaniciYetkileriveKimlikBilgileriCompletedEventHandler KullaniciYetkileriveKimlikBilgileriCompleted;
        
        /// <remarks/>
        public event EBelgeKullaniciCompletedEventHandler EBelgeKullaniciCompleted;
        
        /// <remarks/>
        public event TCGBKullaniciCompletedEventHandler TCGBKullaniciCompleted;
        
        /// <remarks/>
        public event KullanicininYetkileriCompletedEventHandler KullanicininYetkileriCompleted;
        
        /// <remarks/>
        public event KullaniciYetkileriDataSetXMLCompletedEventHandler KullaniciYetkileriDataSetXMLCompleted;
        
        /// <remarks/>
        public event KullaniciYetkileriArrayCompletedEventHandler KullaniciYetkileriArrayCompleted;
        
        /// <remarks/>
        public event getMd5HashCompletedEventHandler getMd5HashCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ABC.gov.tr/KullaniciYetkileri", RequestNamespace="http://ABC.gov.tr/", ResponseNamespace="http://ABC.gov.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Yetki KullaniciYetkileri(string tcno, string sifre, bool memurMu) {
            object[] results = this.Invoke("KullaniciYetkileri", new object[] {
                        tcno,
                        sifre,
                        memurMu});
            return ((Yetki)(results[0]));
        }
        
        /// <remarks/>
        public void KullaniciYetkileriAsync(string tcno, string sifre, bool memurMu) {
            this.KullaniciYetkileriAsync(tcno, sifre, memurMu, null);
        }
        
        /// <remarks/>
        public void KullaniciYetkileriAsync(string tcno, string sifre, bool memurMu, object userState) {
            if ((this.KullaniciYetkileriOperationCompleted == null)) {
                this.KullaniciYetkileriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullaniciYetkileriOperationCompleted);
            }
            this.InvokeAsync("KullaniciYetkileri", new object[] {
                        tcno,
                        sifre,
                        memurMu}, this.KullaniciYetkileriOperationCompleted, userState);
        }
        
        private void OnKullaniciYetkileriOperationCompleted(object arg) {
            if ((this.KullaniciYetkileriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullaniciYetkileriCompleted(this, new KullaniciYetkileriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ABC.gov.tr/KullaniciYetkileriveKimlikBilgileri", RequestNamespace="http://ABC.gov.tr/", ResponseNamespace="http://ABC.gov.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Yetki KullaniciYetkileriveKimlikBilgileri(string tcno, string sifre, bool memurMu) {
            object[] results = this.Invoke("KullaniciYetkileriveKimlikBilgileri", new object[] {
                        tcno,
                        sifre,
                        memurMu});
            return ((Yetki)(results[0]));
        }
        
        /// <remarks/>
        public void KullaniciYetkileriveKimlikBilgileriAsync(string tcno, string sifre, bool memurMu) {
            this.KullaniciYetkileriveKimlikBilgileriAsync(tcno, sifre, memurMu, null);
        }
        
        /// <remarks/>
        public void KullaniciYetkileriveKimlikBilgileriAsync(string tcno, string sifre, bool memurMu, object userState) {
            if ((this.KullaniciYetkileriveKimlikBilgileriOperationCompleted == null)) {
                this.KullaniciYetkileriveKimlikBilgileriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullaniciYetkileriveKimlikBilgileriOperationCompleted);
            }
            this.InvokeAsync("KullaniciYetkileriveKimlikBilgileri", new object[] {
                        tcno,
                        sifre,
                        memurMu}, this.KullaniciYetkileriveKimlikBilgileriOperationCompleted, userState);
        }
        
        private void OnKullaniciYetkileriveKimlikBilgileriOperationCompleted(object arg) {
            if ((this.KullaniciYetkileriveKimlikBilgileriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullaniciYetkileriveKimlikBilgileriCompleted(this, new KullaniciYetkileriveKimlikBilgileriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ABC.gov.tr/EBelgeKullanici", RequestNamespace="http://ABC.gov.tr/", ResponseNamespace="http://ABC.gov.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Yetki EBelgeKullanici(string tcno, string sifre, bool memurMu) {
            object[] results = this.Invoke("EBelgeKullanici", new object[] {
                        tcno,
                        sifre,
                        memurMu});
            return ((Yetki)(results[0]));
        }
        
        /// <remarks/>
        public void EBelgeKullaniciAsync(string tcno, string sifre, bool memurMu) {
            this.EBelgeKullaniciAsync(tcno, sifre, memurMu, null);
        }
        
        /// <remarks/>
        public void EBelgeKullaniciAsync(string tcno, string sifre, bool memurMu, object userState) {
            if ((this.EBelgeKullaniciOperationCompleted == null)) {
                this.EBelgeKullaniciOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEBelgeKullaniciOperationCompleted);
            }
            this.InvokeAsync("EBelgeKullanici", new object[] {
                        tcno,
                        sifre,
                        memurMu}, this.EBelgeKullaniciOperationCompleted, userState);
        }
        
        private void OnEBelgeKullaniciOperationCompleted(object arg) {
            if ((this.EBelgeKullaniciCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EBelgeKullaniciCompleted(this, new EBelgeKullaniciCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ABC.gov.tr/TCGBKullanici", RequestNamespace="http://ABC.gov.tr/", ResponseNamespace="http://ABC.gov.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Yetki TCGBKullanici(string tcno, string sifre, bool memurMu) {
            object[] results = this.Invoke("TCGBKullanici", new object[] {
                        tcno,
                        sifre,
                        memurMu});
            return ((Yetki)(results[0]));
        }
        
        /// <remarks/>
        public void TCGBKullaniciAsync(string tcno, string sifre, bool memurMu) {
            this.TCGBKullaniciAsync(tcno, sifre, memurMu, null);
        }
        
        /// <remarks/>
        public void TCGBKullaniciAsync(string tcno, string sifre, bool memurMu, object userState) {
            if ((this.TCGBKullaniciOperationCompleted == null)) {
                this.TCGBKullaniciOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTCGBKullaniciOperationCompleted);
            }
            this.InvokeAsync("TCGBKullanici", new object[] {
                        tcno,
                        sifre,
                        memurMu}, this.TCGBKullaniciOperationCompleted, userState);
        }
        
        private void OnTCGBKullaniciOperationCompleted(object arg) {
            if ((this.TCGBKullaniciCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TCGBKullaniciCompleted(this, new TCGBKullaniciCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ABC.gov.tr/KullanicininYetkileri", RequestNamespace="http://ABC.gov.tr/", ResponseNamespace="http://ABC.gov.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User KullanicininYetkileri(string sicil, string sifre, bool memurMu, int projeId) {
            object[] results = this.Invoke("KullanicininYetkileri", new object[] {
                        sicil,
                        sifre,
                        memurMu,
                        projeId});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void KullanicininYetkileriAsync(string sicil, string sifre, bool memurMu, int projeId) {
            this.KullanicininYetkileriAsync(sicil, sifre, memurMu, projeId, null);
        }
        
        /// <remarks/>
        public void KullanicininYetkileriAsync(string sicil, string sifre, bool memurMu, int projeId, object userState) {
            if ((this.KullanicininYetkileriOperationCompleted == null)) {
                this.KullanicininYetkileriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullanicininYetkileriOperationCompleted);
            }
            this.InvokeAsync("KullanicininYetkileri", new object[] {
                        sicil,
                        sifre,
                        memurMu,
                        projeId}, this.KullanicininYetkileriOperationCompleted, userState);
        }
        
        private void OnKullanicininYetkileriOperationCompleted(object arg) {
            if ((this.KullanicininYetkileriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullanicininYetkileriCompleted(this, new KullanicininYetkileriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ABC.gov.tr/KullaniciYetkileriDataSetXML", RequestNamespace="http://ABC.gov.tr/", ResponseNamespace="http://ABC.gov.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string KullaniciYetkileriDataSetXML(string tcno, string sifre, bool memurMu) {
            object[] results = this.Invoke("KullaniciYetkileriDataSetXML", new object[] {
                        tcno,
                        sifre,
                        memurMu});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void KullaniciYetkileriDataSetXMLAsync(string tcno, string sifre, bool memurMu) {
            this.KullaniciYetkileriDataSetXMLAsync(tcno, sifre, memurMu, null);
        }
        
        /// <remarks/>
        public void KullaniciYetkileriDataSetXMLAsync(string tcno, string sifre, bool memurMu, object userState) {
            if ((this.KullaniciYetkileriDataSetXMLOperationCompleted == null)) {
                this.KullaniciYetkileriDataSetXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullaniciYetkileriDataSetXMLOperationCompleted);
            }
            this.InvokeAsync("KullaniciYetkileriDataSetXML", new object[] {
                        tcno,
                        sifre,
                        memurMu}, this.KullaniciYetkileriDataSetXMLOperationCompleted, userState);
        }
        
        private void OnKullaniciYetkileriDataSetXMLOperationCompleted(object arg) {
            if ((this.KullaniciYetkileriDataSetXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullaniciYetkileriDataSetXMLCompleted(this, new KullaniciYetkileriDataSetXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ABC.gov.tr/KullaniciYetkileriArray", RequestNamespace="http://ABC.gov.tr/", ResponseNamespace="http://ABC.gov.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Yetkiler[] KullaniciYetkileriArray(string tcno, string sifre, bool memurMu) {
            object[] results = this.Invoke("KullaniciYetkileriArray", new object[] {
                        tcno,
                        sifre,
                        memurMu});
            return ((Yetkiler[])(results[0]));
        }
        
        /// <remarks/>
        public void KullaniciYetkileriArrayAsync(string tcno, string sifre, bool memurMu) {
            this.KullaniciYetkileriArrayAsync(tcno, sifre, memurMu, null);
        }
        
        /// <remarks/>
        public void KullaniciYetkileriArrayAsync(string tcno, string sifre, bool memurMu, object userState) {
            if ((this.KullaniciYetkileriArrayOperationCompleted == null)) {
                this.KullaniciYetkileriArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKullaniciYetkileriArrayOperationCompleted);
            }
            this.InvokeAsync("KullaniciYetkileriArray", new object[] {
                        tcno,
                        sifre,
                        memurMu}, this.KullaniciYetkileriArrayOperationCompleted, userState);
        }
        
        private void OnKullaniciYetkileriArrayOperationCompleted(object arg) {
            if ((this.KullaniciYetkileriArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KullaniciYetkileriArrayCompleted(this, new KullaniciYetkileriArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ABC.gov.tr/getMd5Hash", RequestNamespace="http://ABC.gov.tr/", ResponseNamespace="http://ABC.gov.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getMd5Hash(string input) {
            object[] results = this.Invoke("getMd5Hash", new object[] {
                        input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMd5HashAsync(string input) {
            this.getMd5HashAsync(input, null);
        }
        
        /// <remarks/>
        public void getMd5HashAsync(string input, object userState) {
            if ((this.getMd5HashOperationCompleted == null)) {
                this.getMd5HashOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMd5HashOperationCompleted);
            }
            this.InvokeAsync("getMd5Hash", new object[] {
                        input}, this.getMd5HashOperationCompleted, userState);
        }
        
        private void OngetMd5HashOperationCompleted(object arg) {
            if ((this.getMd5HashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMd5HashCompleted(this, new getMd5HashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ABC.gov.tr/")]
    public partial class Yetki {
        
        private System.Data.DataSet dsField;
        
        private string msgField;
        
        private string adSoyadField;
        
        /// <remarks/>
        public System.Data.DataSet Ds {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public string AdSoyad {
            get {
                return this.adSoyadField;
            }
            set {
                this.adSoyadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ABC.gov.tr/")]
    public partial class Yetkiler {
        
        private string firmaNoField;
        
        private string msgField;
        
        private int profilIdField;
        
        private string cpflField;
        
        private string profilAciklamaField;
        
        private string profilAdField;
        
        private string cburField;
        
        private string tcnoField;
        
        /// <remarks/>
        public string FirmaNo {
            get {
                return this.firmaNoField;
            }
            set {
                this.firmaNoField = value;
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public int ProfilId {
            get {
                return this.profilIdField;
            }
            set {
                this.profilIdField = value;
            }
        }
        
        /// <remarks/>
        public string Cpfl {
            get {
                return this.cpflField;
            }
            set {
                this.cpflField = value;
            }
        }
        
        /// <remarks/>
        public string ProfilAciklama {
            get {
                return this.profilAciklamaField;
            }
            set {
                this.profilAciklamaField = value;
            }
        }
        
        /// <remarks/>
        public string ProfilAd {
            get {
                return this.profilAdField;
            }
            set {
                this.profilAdField = value;
            }
        }
        
        /// <remarks/>
        public string Cbur {
            get {
                return this.cburField;
            }
            set {
                this.cburField = value;
            }
        }
        
        /// <remarks/>
        public string Tcno {
            get {
                return this.tcnoField;
            }
            set {
                this.tcnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ABC.gov.tr/")]
    public partial class User {
        
        private int profilIdField;
        
        private string kimlikNoField;
        
        private string adSoyadField;
        
        private string sicilField;
        
        private string yetkiField;
        
        private string msgField;
        
        private bool authenticatedField;
        
        private bool authrizedField;
        
        private string aBCField;
        
        /// <remarks/>
        public int ProfilId {
            get {
                return this.profilIdField;
            }
            set {
                this.profilIdField = value;
            }
        }
        
        /// <remarks/>
        public string KimlikNo {
            get {
                return this.kimlikNoField;
            }
            set {
                this.kimlikNoField = value;
            }
        }
        
        /// <remarks/>
        public string AdSoyad {
            get {
                return this.adSoyadField;
            }
            set {
                this.adSoyadField = value;
            }
        }
        
        /// <remarks/>
        public string Sicil {
            get {
                return this.sicilField;
            }
            set {
                this.sicilField = value;
            }
        }
        
        /// <remarks/>
        public string Yetki {
            get {
                return this.yetkiField;
            }
            set {
                this.yetkiField = value;
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public bool Authenticated {
            get {
                return this.authenticatedField;
            }
            set {
                this.authenticatedField = value;
            }
        }
        
        /// <remarks/>
        public bool Authrized {
            get {
                return this.authrizedField;
            }
            set {
                this.authrizedField = value;
            }
        }
        
        /// <remarks/>
        public string ABC {
            get {
                return this.aBCField;
            }
            set {
                this.aBCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void KullaniciYetkileriCompletedEventHandler(object sender, KullaniciYetkileriCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullaniciYetkileriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullaniciYetkileriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Yetki Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Yetki)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void KullaniciYetkileriveKimlikBilgileriCompletedEventHandler(object sender, KullaniciYetkileriveKimlikBilgileriCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullaniciYetkileriveKimlikBilgileriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullaniciYetkileriveKimlikBilgileriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Yetki Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Yetki)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void EBelgeKullaniciCompletedEventHandler(object sender, EBelgeKullaniciCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EBelgeKullaniciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EBelgeKullaniciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Yetki Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Yetki)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void TCGBKullaniciCompletedEventHandler(object sender, TCGBKullaniciCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TCGBKullaniciCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TCGBKullaniciCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Yetki Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Yetki)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void KullanicininYetkileriCompletedEventHandler(object sender, KullanicininYetkileriCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullanicininYetkileriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullanicininYetkileriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void KullaniciYetkileriDataSetXMLCompletedEventHandler(object sender, KullaniciYetkileriDataSetXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullaniciYetkileriDataSetXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullaniciYetkileriDataSetXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void KullaniciYetkileriArrayCompletedEventHandler(object sender, KullaniciYetkileriArrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KullaniciYetkileriArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KullaniciYetkileriArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Yetkiler[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Yetkiler[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void getMd5HashCompletedEventHandler(object sender, getMd5HashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMd5HashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMd5HashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591